export const EMAIL_COLLECTION_FORM_SUBMIT_START =
  "EMAIL_COLLECTION_FORM_SUBMIT_START";
export const EMAIL_COLLECTION_SUCCESS = "EMAIL_COLLECTION_SUCCESS";
export const COMPLETE_EMAIL_COLLECTION = "COMPLETE_EMAIL_COLLECTION";
